### ISSUE TITLE
Change `PreTrainedBertModel` to `BertPreTrainedModel`

### ISSUE THREAD

**Issue by tnlin** [kaushaltrivedi/bert-toxic-comments-multilabel#1]
Hi, thanks for sharing this wonderful work
I recently try to re-run the code and cannot import the pytorch_pretrained_bert correctly
and I figure out the module in  huggingface/pytorch-pretrained-BERT have changed from `PreTrainedBertModel` to `BertPreTrainedModel`,  just a reminder for those who facing the same issue

**Comment by kaushaltrivedi** [comment]
Done :)

**Comment by omri374** [comment]
Hey @kaushaltrivedi great work! Worth mentioning this on the blog post too! I found myself looking for `PreTrainedBertModel` but couldn't find it anywhere.
