### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'BERT\\pytorch_model.bin'

### ISSUE THREAD

**Issue by grossal** [kaushaltrivedi/bert-toxic-comments-multilabel#14]
I tried to rerun the code and get the file not found Error. Where can I download the pytorch_model.bin? Or what method do I need to use? I can't find anything helpful on the net.

I tried to download the model with "BertModel.from_pretrained('bert-base-uncased')", but couldn't find the pytorch_model.bin.

**Comment by parthplc** [comment]
how did you solve it?
