### ISSUE TITLE
What is in the classes.txt file?

### ISSUE THREAD

**Issue by negacy** [kaushaltrivedi/bert-toxic-comments-multilabel#2]
Great work, thanks for sharing, @kaushaltrivedi . I am trying to run this code, but having issues related to the input data. I downloaded the [dataset](https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge/data) from Kaggle. But, it looks like there are missing files like the classes.txt. Could you please explain the format of those?

Thanks.

**Comment by kaushaltrivedi** [comment]
I have added the classes.txt file
